<?php

namespace App\Console\Commands;

use App\Http\Middleware\EnsureOpsToken;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Str;

/**
 * Everything the maintenance advisor needs to reach this environment.
 *
 * It exists for one reason that is not obvious: **the telemetry URL cannot be
 * typed.** It carries a signature derived from `APP_KEY`, so it has to be
 * generated by the application it points at — and it is different in every
 * environment. Hand-composing it produces a 403 that looks like a broken
 * endpoint rather than a missing signature.
 *
 * PRINTS, never writes. `.env` holds real secrets in every environment this
 * would run in, and a command that rewrites it is a command that will one day
 * mangle one.
 */
class AdvisorSetupCommand extends Command
{
    protected $signature = 'cfb:advisor-setup {--rotate : Print a fresh token instead of reading the configured one}';

    protected $description = "Print the advisor's token, its signed telemetry URL, and the routine's configuration";

    public function handle(): int
    {
        $configured = (string) config('cfb.ops_token');
        $rotating = $this->option('rotate') || mb_strlen($configured) < EnsureOpsToken::MINIMUM_LENGTH;

        // 64 hex characters. Comfortably past the minimum, and safe to paste
        // through a shell, a YAML file and an environment panel unquoted.
        $token = $rotating ? Str::random(64) : $configured;

        $this->newLine();

        if ($rotating) {
            $this->line('  <fg=yellow>No usable OPS_TOKEN is configured.</> Add this line, then run again:');
            $this->newLine();
            $this->line("  <fg=green>OPS_TOKEN={$token}</>");
            $this->newLine();
            $this->line('  <fg=gray>Both /ops routes answer 404 until it is set — an ops surface');
            $this->line('  nobody configured should not announce that it exists.</>');
            $this->newLine();

            // Non-zero: nothing below is usable yet, and this is the shape a
            // deploy check would want to fail on.
            return self::FAILURE;
        }

        $this->line('  <fg=gray>The advisor reads this, and files back through the other:</>');
        $this->newLine();
        $this->line('  <fg=green>GET </> '.URL::signedRoute('ops.telemetry'));
        $this->line('  <fg=green>POST</> '.route('ops.workbook'));
        $this->newLine();
        $this->line('  <fg=gray>Header on both:</> '.EnsureOpsToken::HEADER.': <fg=yellow>'.$this->masked($token).'</>');
        $this->newLine();
        $this->line('  <fg=gray>The GET URL carries a signature derived from APP_KEY, so it cannot');
        $this->line('  be typed and it differs per environment. Copy it verbatim.</>');
        $this->newLine();

        return self::SUCCESS;
    }

    /**
     * The token is already in the environment of whoever can run this, so the
     * masking is not a secret boundary — it is so a screen share, a scrollback
     * or a CI log does not hand it to somebody who could not already read it.
     */
    private function masked(string $token): string
    {
        return mb_substr($token, 0, 6).str_repeat('•', 12).mb_substr($token, -4);
    }
}
