<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Phase 5's whole footprint: groups, contests, weekly slates, picks, and the
 * Conversation. Eight tables in one migration because they only make sense
 * together — a slate without a contest or a pick without a slate game is not
 * a partial feature, it is a broken one.
 *
 * Null semantics carry the app's founding rule into the schema. Null always
 * means "no data yet": a draft slate game's spread is null until publish
 * freezes a line onto it, a pick's result is null until the game is graded,
 * and a missed pick is an ABSENT ROW — `picked_team_id` is NOT NULL because
 * there is no such thing as a null pick, and nothing ever writes one on the
 * user's behalf.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('groups', function (Blueprint $table) {
            $table->id();
            $table->string('name', 40);
            // The invite IS the code — no invites table in v1. Uppercase
            // alphanumeric, generated by CreateGroup, never user-chosen.
            $table->char('code', 8)->unique();
            // 'private' (join by code) or 'lobby' (house-run, open join).
            $table->string('kind', 10);
            $table->timestamps();
        });

        Schema::create('group_members', function (Blueprint $table) {
            $table->id();
            $table->foreignId('group_id')->constrained()->cascadeOnDelete();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            // 'commissioner' or 'member'. A role on the membership rather than
            // an owner_id on the group, so a handoff is one UPDATE and the
            // group never carries a second copy of who runs it.
            $table->string('role', 12);
            $table->timestamps();

            $table->unique(['group_id', 'user_id']);
            // "My groups" is the hottest membership query and the unique
            // above leads with group_id, which that query cannot use — the
            // athlete_season_stats lesson, applied before it costs anything.
            $table->index('user_id');
        });

        Schema::create('contests', function (Blueprint $table) {
            $table->id();
            $table->foreignId('group_id')->constrained()->cascadeOnDelete();
            /*
             * The YEAR, not a season_id: a CFB year spans several `seasons`
             * rows (preseason through postseason), and a contest that slates
             * a postseason Saturday would cross season_id mid-run. Written
             * from CfbCalendar at creation, never from config.
             */
            $table->unsignedSmallInteger('season_year');
            // Backing value of App\Enums\ContestMode. 'tiered' stays neutral
            // on purpose — the product name (Triple Option) lives in Voice
            // and labels, never in data.
            $table->string('mode', 12);
            // Mode-specific rule knobs, and The Woodshed's landing pad: its
            // rules arrive as engine code plus settings, zero schema churn.
            // Null means "mode defaults" — never an empty object.
            $table->json('settings')->nullable();
            $table->timestamps();

            $table->unique(['group_id', 'season_year', 'mode']);
        });

        Schema::create('slates', function (Blueprint $table) {
            $table->id();
            $table->foreignId('contest_id')->constrained()->cascadeOnDelete();
            $table->foreignId('week_id')->constrained();
            // 'draft' | 'published' | 'settled'.
            $table->string('status', 10);
            $table->timestamp('published_at')->nullable();
            // Also the settlement CLAIM: SettleSlate's atomic
            // whereNull-then-update on this column is what makes a
            // double-fired settlement pay nobody twice.
            $table->timestamp('settled_at')->nullable();
            // The commissioner-designated total-points game. FK added after
            // slate_games exists, below.
            $table->unsignedBigInteger('tiebreaker_slate_game_id')->nullable();
            $table->timestamps();

            $table->unique(['contest_id', 'week_id']);
        });

        Schema::create('slate_games', function (Blueprint $table) {
            $table->id();
            $table->foreignId('slate_id')->constrained()->cascadeOnDelete();
            $table->unsignedInteger('game_id');
            // Null means "this mode has no tiers" (Classic) — never a
            // default 1. The tiered engine requires 1-3 at publish.
            $table->unsignedTinyInteger('tier')->nullable();
            // The commissioner's display order within the board.
            $table->unsignedTinyInteger('position');
            /*
             * THE FROZEN LINE, copied from game_odds' `current` phase at
             * publish — that row is rewritten in place by every sync, so a
             * reference could never hold still. Same convention and width
             * as its source, decimal(5,1): the value is ESPN's, which is
             * the HOME team's handicap (positive = road favorite), so the
             * MAGNITUDE is the favorite's burden and favorite_team_id says
             * whose. Null while drafting (the line may not exist yet);
             * publish validation requires it. Grading reads THIS number and
             * only this number, whatever the market did after.
             */
            $table->decimal('spread', 5, 1)->nullable();
            $table->unsignedMediumInteger('favorite_team_id')->nullable();
            // Provenance: whose number this was and when it was captured.
            $table->string('odds_provider', 40)->nullable();
            $table->timestamp('odds_captured_at')->nullable();
            $table->timestamps();

            $table->foreign('game_id')->references('id')->on('games')->cascadeOnDelete();
            $table->foreign('favorite_team_id')->references('id')->on('teams')->nullOnDelete();

            $table->unique(['slate_id', 'game_id']);
            // The grading recompute's entry query — "which slate games carry
            // game X?" — which the unique above (leading slate_id) cannot
            // serve. One index, one named query.
            $table->index('game_id');

            // There is deliberately no points_value column: a pick's value is
            // f(mode, tier), computed by the mode engine. A stored copy is a
            // derived column waiting to disagree with contests.mode.
        });

        Schema::table('slates', function (Blueprint $table) {
            $table->foreign('tiebreaker_slate_game_id')
                ->references('id')->on('slate_games')->nullOnDelete();
        });

        Schema::create('picks', function (Blueprint $table) {
            $table->id();
            $table->foreignId('slate_game_id')->constrained()->cascadeOnDelete();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            // NOT NULL: a missed pick is an absent row, never a null one.
            $table->unsignedMediumInteger('picked_team_id');
            // 'win' | 'loss' | 'push'; null = not yet graded.
            $table->string('result', 5)->nullable();
            /*
             * Null and zero mean DIFFERENT things here: null = ungraded,
             * 0 = graded and earned nothing (a loss, or a push under the
             * push-pays-zero rule). Callers must never conflate them.
             */
            $table->unsignedTinyInteger('points')->nullable();
            // updated_at is meaningful: picks are mutable until kickoff.
            $table->timestamps();

            // Teams never delete in practice; if one ever did, a graded pick
            // is history and must refuse to vanish with it — so no cascade.
            $table->foreign('picked_team_id')->references('id')->on('teams');

            // Serves grading's whereIn(slate_game_id) as well as uniqueness.
            $table->unique(['slate_game_id', 'user_id']);
            // "My season record."
            $table->index('user_id');
        });

        Schema::create('slate_entries', function (Blueprint $table) {
            $table->id();
            $table->foreignId('slate_id')->constrained()->cascadeOnDelete();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            /*
             * Predicted combined total of the tiebreaker game. Null = never
             * entered one, and at settlement a null LOSES to any non-null —
             * never substituted with 0, which would otherwise be an
             * accidentally strong guess in a defensive slugfest.
             */
            $table->unsignedSmallInteger('tiebreaker_total')->nullable();
            $table->timestamps();

            $table->unique(['slate_id', 'user_id']);
            $table->index('user_id');

            // No stored weekly totals or ranks: leaderboards are SUMs over
            // picks (a group times fifteen rows a week), the walletTotals()
            // philosophy. Materialize only behind a measurement.
        });

        Schema::create('conversation_posts', function (Blueprint $table) {
            $table->id();
            // Enforced morph map: 'game' | 'team' | 'group'. Wide enough for
            // games (int), teams (mediumint) and groups (bigint).
            $table->string('topic_type', 10);
            $table->unsignedBigInteger('topic_id');
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->string('body', 500);
            // No updated_at — posts are immutable rows, the ledger shape.
            // Moderation deletes; it never edits.
            $table->timestamp('created_at')->useCurrent();

            // The one read pattern: this topic's posts, newest last. `id` as
            // the trailing column satisfies the ORDER BY with no filesort.
            $table->index(['topic_type', 'topic_id', 'id']);

            // No conversations parent table: a conversation IS the
            // (type, id) pair, and a parent row would only add a
            // firstOrCreate race for nothing to hang off it.
        });
    }

    public function down(): void
    {
        // slates ⇄ slate_games reference each other; break the cycle first.
        Schema::table('slates', function (Blueprint $table) {
            $table->dropForeign(['tiebreaker_slate_game_id']);
        });

        Schema::dropIfExists('conversation_posts');
        Schema::dropIfExists('slate_entries');
        Schema::dropIfExists('picks');
        Schema::dropIfExists('slate_games');
        Schema::dropIfExists('slates');
        Schema::dropIfExists('contests');
        Schema::dropIfExists('group_members');
        Schema::dropIfExists('groups');
    }
};
